name: interactive_json_preview
description: A pretty interactive JSON viewer
homepage: https://github.com/yeikel16/interactive_json_preview
repository: https://github.com/yeikel16/interactive_json_preview
version: 0.0.1

topics:
  - widget
  - ui
  - json
  - preview
  - interactive

environment:
  sdk: "^3.3.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
