name: interactive_json_preview
description: A pretty interactive JSON viewer to improve readability. Collapses and expands sections in which JSON objects are complex at a glance.
homepage: https://github.com/yeikel16/interactive_json_preview
repository: https://github.com/yeikel16/interactive_json_preview.git
version: 0.0.1+1

topics:
  - widget
  - ui
  - json
  - preview
  - interactive

screenshots:
  - description: 'This GIF show how collapses and expands sections in which JSON objects are complex at a glance.'
    path: assets/view.webp
  - description: 'A pretty interactive JSON viewer to improve readability.'
    path: assets/image-1.png

environment:
  sdk: "^3.3.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
